baseurl = "https://rmccarth.info/"
languageCode = "en-us"
theme = "hugo-theme-terminal"
paginate = 5

[params]
  contentTypeName = "post"
  themeColor = "orange"
  showMenuItems = 0
  fullWidthTheme = false
  centerTheme = false

[languages]
  [languages.en]
    title = "$ whoami"
    subtitle = "A simple, retro theme for Hugo"
    keywords = ""
    copyright = ""
    menuMore = "$ ping localhost"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "$ whoami"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "contact"
        url = "/about"

    [[languages.en.menu.main]]
        identifier = "showcase"
        name = "medium"
        url = "https://medium.com/@rob.mccarthy31"

    [[languages.en.menu.main]]
        identifier = "github"
        name = "github"
        url = "https://github.com/rmccarth"
